version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "REPLACE_TASK_ARN"
        LoadBalancerInfo: 
          ContainerName: "app"
          ContainerPort: "3000"